//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcademyApplication.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Option
    {
        public int OptionID { get; set; }
        public int QuestionID { get; set; }
        public string OptionAnswer { get; set; }
        public int Sequence { get; set; }
        public bool IsHaveImage { get; set; }
    
        public virtual Question Question { get; set; }
    }
}
