//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcademyApplication.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionGroup
    {
        public QuestionGroup()
        {
            this.Results = new HashSet<Result>();
            this.Questions = new HashSet<Question>();
        }
    
        public int QuestionGroupID { get; set; }
        public string QuestionGroupName { get; set; }
        public bool IsValid { get; set; }
    
        public virtual ICollection<Result> Results { get; set; }
        public virtual ICollection<Question> Questions { get; set; }
    }
}
