//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcademyApplication.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        public Question()
        {
            this.Options = new HashSet<Option>();
        }
    
        public int QuestionID { get; set; }
        public string Question1 { get; set; }
        public int Answer { get; set; }
        public int QuestionGroupID { get; set; }
        public int QuestionTypeID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public bool IsValid { get; set; }
        public bool IsHaveImage { get; set; }
    
        public virtual ICollection<Option> Options { get; set; }
        public virtual QuestionGroup QuestionGroup { get; set; }
        public virtual QuestionType QuestionType { get; set; }
    }
}
